# Generated by Django 2.1.5 on 2020-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qns',
            fields=[
                ('qn_id', models.IntegerField(primary_key=True, serialize=False)),
                ('qn', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('correct', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'qns',
                'managed': True,
            },
        ),
    ]
